cat("map_output_startingterr()  -  ")

 
  
     
 
################## https://github.com/r-spatial/sf/issues/406   UPDATE
 


####################################################################################################### FUN: mapsim_update_function_init - generate side panel map on TAB 2 incl. release points and init terrs
 # lay_release_pts = reactive: release points generated by user
 # lay_release_pts_new= reactive: relocated translocation points if needed
 # mapsim_init0 = reactive: base map for init terrs  stored in rvplot1
 # start_pop=  reactive: rvsim$start_pop contains starting territories simulation output 
 # sim_objective= user input: input$sim_objective, what layer to display "starting territories" etc
 # Nfams_init_d_ = reactive: debounced user input value Nfams_init_d()

FUN_map_output_startingterr <-function(mapsim_init0,start_pop,lay_release_pts,lay_release_pts_new,rvplot1, sim_objective, Nfams_init_d_ ){ ## update with initial conds # small side map
cat("function: map_output_startingterr\n")
           update_busy_bar(10) 
           start_terr <- start_pop[start_pop$layer =="starting territories" ,]       
   
        
           
       if( is.null(mapsim_init0)) {
                        cat("new extent  -  ")
                        #start_terr <- start_pop[start_pop$layer =="starting territories" ,]    
                   
                       if(nrow(start_terr)>0) {    mapped_features <-   st_union(st_union(start_terr),st_union(lay_release_pts)  )
                                                       mapped_bbox <- st_bbox(mapped_features) }
                       if(nrow(start_terr)==0) {   mapped_features <-    st_union(lay_release_pts)     
                                                       mapped_bbox <- st_bbox(mapped_features) }
                        update_busy_bar(20)   
                            new_ext0 <-  st_as_sfc(  st_bbox (st_buffer(mapped_features,3000) ) )  
                            st_crs(new_ext0) <- mercproj 
                            rvplot1$LocalHab <- st_crop(HabMapLayers,new_ext0) 
                            rvplot1$ext_coastline  <- st_crop(coastline , new_ext0)  
                            rvplot1$ext_region_box <-  st_crop(region_box,new_ext0) 
                            rvplot1$riv  <- st_union( st_crop( rivlines,new_ext0) ) 
                            cat("GIS layers cropped  -  ") 
                            update_busy_bar(30) 
                            if(length(rvplot1$riv)>0){ rvplot1$LocalHab <- rbind(rvplot1$LocalHab, st_sf(geometry= rvplot1$riv , layer="river") )   }               
                            rvplot1$LocalBackLayers  <- st_crop(BackLayers,new_ext0) 
                            rvplot1$LocalBackText    <- st_intersection(BackText,new_ext0) 
                            rvplot1$LocalBackPoints    <- st_intersection(BackPoints,new_ext0) 
                                    
                       ## {} was here
                        mapsim_init0 <-  ggplot( ) + 
                                            geom_sf(data =  rvplot1$ext_region_box, col=NA, fill="white")+
                                            geom_sf(data =  rvplot1$ext_region_box, col=NA, fill="steelblue", alpha=.9)+
                                            geom_sf(data =  rvplot1$ext_coastline ,  fill="beige", col="steelblue", alpha=.9, size=1)   +
                                            geom_sf(data= rvplot1$LocalHab [rvplot1$LocalHab$layer %in% c("suitable","dispersal"),] ,  mapping = aes(fill= layer , col= layer), alpha=.4, size=0 ) + 
                                            geom_sf(data=   rvplot1$riv , col=alpha("skyblue",.7),fill=alpha("steelblue",.8), size=2)+ 
                                            geom_sf(data=   rvplot1$riv , col=alpha("steelblue",.9),fill=alpha("skyblue",.7), size=1)+  
                                            geom_sf(data=rvplot1$LocalBackLayers [rvplot1$LocalBackLayers$layer %in% c("b road","a road","minor road","primary road")  ,], col= "yellow", size=.8,alpha=.8 )+
                                            geom_sf(data=rvplot1$LocalBackLayers [rvplot1$LocalBackLayers$layer %in% c("railway line")  ,], linetype="dotted", col= 1, size=3  )+
                                            geom_sf(data=rvplot1$LocalBackPoints  , aes(col=layer,  shape=layer), size=3, stroke=1 )+
                                            geom_sf_text (data=rvplot1$LocalBackText [ rvplot1$LocalBackText$layer2 != "Railway Station",], aes(label=label, col=layer2, size=layer2 )   )+
                                            geom_sf_label(data=rvplot1$LocalBackText [rvplot1$LocalBackText$layer2  == "Railway Station",], aes(label=label),fill=alpha(1,.4), col="beige")+ 
                        
                                            scale_fill_manual(values=c(   "suitable"=alpha("turquoise3",.3), "dispersal"=alpha("olivedrab4",.3), "unsuitable"=alpha("honeydew3",.4), "river"="steelblue",
                                                                           "a road"="brown", "b road"="orange", "admin line"="black",
                                                                           "TV or radio mast or tower"="blue","Wind powered generator"="blue","foreshor region"=alpha("lightseagreen",.7),
                                                                           "marsh"="green","woodland region"=alpha("olivedrab4",.7),"urban region"="purple","rivers line"=alpha("skyblue",.8),"lakes region"=alpha("steelblue",.9),
                                                                           "minor road"=alpha("grey",.6),"primary road"="red","railway line"="black" ,
                                                                            "Loch"=0, "Forest"=0,  "named places"=0,  "road names"=0, "local altitude"="purple"   ))+
                                         
                                             scale_colour_manual(values=c( "suitable"=0, "dispersal"=0, "unsuitable"=0, "river"="steelblue","a road"="brown", "b road"="orange", "admin line"="black",
                                                                           "TV or radio mast or tower"="blue","Wind powered generator"="blue","foreshor region"=0,
                                                                           "marsh"="green","woodland region"=0,"urban region"=0,"rivers line"=alpha("skyblue",.8),"lakes region"= 0,
                                                                           "minor road"=alpha("grey",.6),"primary road"="red","railway line"="black",
                                                                           "Loch"="steelblue4","Forest"="green4",  "named places"=1, "road names"="grey30", "local altitude"="purple"   )  )+  
                                           
                                             scale_shape_manual(values=c( "TV or radio mast or tower"=13,"Wind powered generator"=8,"foreshor region"=0,
                                                                           "marsh"=8,"woodland region"=0,"urban region"=0,"rivers line"=0,"lakes region"= 0,
                                                                           "minor road"=0,"primary road"=0,"railway line"=0,
                                                                            "Loch"=0,"Forest"=0,  "named places"=0, "road names"=0, "local altitude"=17)  )+  
                                      
                                             scale_size_manual(values=c( "a road"=2, "b road"=1.5, "admin line"=1, "admin seed"=5,
                                                                            "TV or radio mast or tower"=3,"Wind powered generator"=3,"foreshor region"=0,
                                                                            "marsh"=3,"woodland region"=0,"urban region"=0,"rivers line"=2,"lakes region"= 0,
                                                                            "minor road"=1,"primary road"=1.5,"railway line"=2,
                                                                            "Loch"=4.5,"Forest"=4, "named places"=4, "road names"=3, "local altitude"=3)  )+  
                                              annotation_scale(location = "bl")+
                                              coord_sf(crs = mercproj, expand=F) +
                                              theme(legend.position = "none", axis.title.x = element_blank(), 
                                              axis.title.y = element_blank(),  axis.text = element_blank(),    
                                              panel.border = element_rect(fill =NA) ,
                                              plot.background = element_rect(fill = "transparent", colour = NA)) 
       }
                   
              update_busy_bar(60)               
                       
       if(length(sim_objective)==0) {mapsim_init  <-  mapsim_init0 } else {
         
               req(!is.null(mapsim_init0)  & length(sim_objective)>0  )
                plotfills <- rep("magenta",Nfams_init_d_) 
              
               mapsima <- mapsimb <- mapsimc <-  mapsim_init0
                       
               if("starting territories" %in% sim_objective) {
                      start_terr$family <-  as.factor(start_terr$family)
                     mapsima <-mapsimb<- mapsimc + new_scale_fill() +  scale_fill_manual("", values=plotfills, drop=FALSE)+
                                                   geom_sf(data=start_terr ,  fill= "magenta" ,col=1)
                     mapsim_init <-  mapsima +  coord_sf(crs = mercproj, expand=F) + annotation_scale(location = "bl")
               }
               
              update_busy_bar(80) 
              if("release points (initial)" %in% sim_objective) {
                    lay_release_pts$family <- as.factor(lay_release_pts$family)
                    mapsima  <- mapsimb  + new_scale_fill() +  scale_fill_manual("", values=rainbow(10)[seq(1,Nfams_init_d_)], drop=FALSE)+ 
                                           geom_sf(data=lay_release_pts, aes(fill= family  ), stroke=2,   size=3,  shape=21)#+  
                    mapsim_init <-  mapsima +  coord_sf(crs = mercproj, expand=F) + annotation_scale(location = "bl")
               } 
               update_busy_bar(90) 
               if("release points (relocated)" %in% sim_objective) {
                    lay_release_pts_new$family <- as.factor(lay_release_pts_new$family)
                     mapsima  <- mapsima + geom_sf(data=lay_release_pts_new,   size=5, stroke=2,  shape=4)  
                     mapsim_init <-  mapsima +  coord_sf(crs = mercproj, expand=F) + annotation_scale(location = "bl")
                           }
       } 
  ("plot data ready\n")
 update_busy_bar(100) 
 return(list(mapsim_init,mapsim_init0))
}
  

