cat("dl_output_content()  -  ")
 




FUN_dl_output_content <- function(filename,file, sim_pop,start_pop,mgmt.years,locname ,out_chulls,out_Nruns,Nfams_init_d_ ,Nfams,lay_release_pts_new,Nfams_wYoung,Nsites,demog,buffer_sel,y,x,Nads,Nyoungs,Nfams_w2Young,famsettled_text,ext_area_sel,Ngroups) {

  cat("compile output for saving\nfunction: dl_output_content\n")

          # temp  wdir
        owd <- setwd( tempdir())
        on.exit( setwd(owd))
        #unlink(tempdir(), recursive = T)
        txt_sim <- paste0("Population growth was not simulated.\n")
           if(!is.null(sim_pop)) {
             txt_sim <- paste0("Population growth was simulated over ",mgmt.years, " years for 15 runs considering similar starting territories.\n")
             cat(paste0("reference: ", locname,"  -  ")) 
        # result table
          write.csv(sim_pop[[3]], paste0("SimTable_",locname,".csv"), row.names = FALSE ) 
       cat("table  -  ")
        # shapefiles - Nruns
         shp_loc <- paste0(file.path(tempdir()) , "/SimNruns_",locname) 
         my_dsn <- paste0( shp_loc,".shp")
         sf::st_write(out_Nruns, dsn =  my_dsn, driver = "ESRI Shapefile", quiet = TRUE,append=FALSE)
        cat("runs shapefiles  -  ")
        # shapefiles - conv hulls
         shp_loc2 <- paste0(file.path(tempdir()) , "/SimChulls_",locname)
         my_dsn2 <- paste0( shp_loc2,".shp")
         sf::st_write(out_chulls, dsn =  my_dsn2, driver = "ESRI Shapefile", quiet = TRUE,append=FALSE)
        cat("convex hulls shapefiles  -  ")
          }  
        if(!is.null(start_pop)){ 
           # result text 
             NsitesChoices <- c(" automated release locations."="random_location_across.",
                           " locate each release point."="each_pt_on_map.",
                           " start from a single release point."="single_release_pt" ) 
        
              if(Nfams == Nfams_init_d_) {Nfamstext <- paste0(Nfams_init_d_, " initial groups of beavers (")} else {
               Nfamstext <- paste0(Nfams, " initial groups of beavers, reduced from ",Nfams_init_d_," due to lack of suitable space (") }
               txt_prot <- paste0("The simulated release included ",Nfamstext , demog,").\n\nThe release point distribution protocol was:", names(NsitesChoices[NsitesChoices==Nsites]) )
               txt_site <- paste0("The candidate release site was a ", round(as.numeric(buffer_sel)/1000,1),"km buffer around centroid point located at x:", 
                                  round(as.numeric(x),-1),"  y:",round(as.numeric(y),-1),".\nCoordinate reference system: +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +units=m +no_defs\n\n")
                txt_init <-  paste0("\n", famsettled_text,  
                        "\n\nThe initial (settled) population contains ",Ngroups ," groups, or a total of ", Nads+Nyoungs ," beavers (", Nads, " adults + ",Nyoungs," young).\n\n",
                        Nfams_w2Young+ Nfams_wYoung  ," groups are with young (",Nfams_w2Young, " with 2 young and ", Nfams_wYoung, " with 1 young).") 
                txt_intro <- paste0( "Outputs downloaded on ",format(as.Date(Sys.Date(), "%y-%m-%d"), "%d %B %Y"),".")
               txt_intro2 <- paste0("Simulations generated by a beaver individual-based model within a shiny App available from ")
               txt_intro3 <- paste0(" https://naturalandenvironmentalscience.shinyapps.io/ScotBeaverTranslocation/")
               txt_intro4 <- paste0(" developed by .zelda. at the University of Newcastle for NatureScot (2022)." )     
               txt_sep <- c("__________________________________________________________________________________________")
               txt_out <-   c(txt_sep,txt_intro,txt_intro2,txt_intro3,txt_intro4, txt_sep, txt_prot, txt_site, txt_sep, txt_init,txt_sep,txt_sim,txt_sep)
      cat("text output  -  ")
          write.csv(txt_out, paste0("SimText_",locname,".txt"),  row.names = FALSE,    quote=FALSE)
          # shapefiles - release points
          shp_loc3 <- paste0(file.path(tempdir()) , "/ReleasePoints_",locname)
          my_dsn3 <- paste0( shp_loc3,".shp")
          sf::st_write(lay_release_pts_new, dsn =  my_dsn3, driver = "ESRI Shapefile", quiet = TRUE,append=FALSE) 
          cat("release points  shapefiles  -  ")
          # shapefiles - init terrs
          shp_loc4 <- paste0(file.path(tempdir()) , "/InitTerrs_",locname)
          my_dsn4 <- paste0( shp_loc4,".shp")
          sf::st_write(st_union(start_pop[start_pop$layer =="starting territories" ,]), dsn =  my_dsn4, driver = "ESRI Shapefile", quiet = TRUE,append=FALSE) 
          cat("starting terrs  shapefiles  -  ")
          # shapefiles - init extent
          shp_loc5 <- paste0(file.path(tempdir()) , "/ReleaseSite_",locname)
          my_dsn5 <- paste0( shp_loc5,".shp")
          sf::st_write( ext_area_sel, dsn =  my_dsn5, driver = "ESRI Shapefile", quiet = TRUE,append=FALSE)   
          }   
  cat("compile  -  ")
      filelist <-   list.files(tempdir(),pattern=locname)    
 
    # Zip them up
      zip( file, filelist)
        cat(" zipped\n")
     
      }